name: prepare
description: prepare development environment

runs:
  using: 'composite'
  steps:
    - uses: cachix/install-nix-action@v30
    - name: Install devenv
      shell: bash
      run: nix profile install nixpkgs#devenv
